### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by lukebakken** [NuwanSameera/fall-detection-algorithm#1]
Hi Nuwan,

I'm opening an issue here because it seems to be the simplest way of sending you a message. If you're on LinkedIn, you can connect via my profile here - https://www.linkedin.com/in/luke-bakken-07552292/

I wanted to say how impressed I am with how quickly you put together a non-trivial modification to RabbitMQ. Please continue to be an active participant in the RabbitMQ community because I'm sure you'll have great feedback from your work with IoT. In fact we're planning to improve RabbitMQ's MQTT support so we'll keep you in mind.

Thanks!

**Comment by NuwanSameera** [comment]
Hi lukebakken,

Thank you for contacting me. I am really happy to work with different platforms. I am unable to sent Contact request to you from my profile. Can you reach me from following one.

https://www.linkedin.com/in/nuwan-sameera-001996115/ 

Thank you.

**Comment by NuwanSameera** [comment]
Hi
 I sent linkdin request t you.

**Comment by lukebakken** [comment]
Got it!
